name: Test macOS ARM64 binary

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-14

    steps:
      - name: System information
        run: |
          sw_vers
          uname -m

      - name: Download and run binary
        run: |
          curl -L --fail -o my1script "https://github.com/Buff220/run-bin-mac/releases/download/v1.0/my1script"
          chmod +x my1script
          file my1script
          ./my1script
